site_name: Transky


#pages:
#- [index.md, home]
#- [second.md, Sec]

theme: readthedocs

nav:
- Home: 'index.md'
- 地面站: 
  - TGA: 'second.md'
- About:
  - License : 'license.md'

markdown_extensions:
  - attr_list